version: '3.1'

services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./raddb/sql:/docker-entrypoint-initdb.d
  radius:
    build: .
    restart: unless-stopped
    depends_on:
      - db